name: Jekyll Themes
url: http://androidfirmware.github.io
description: Flashing Android Firmware OS

permalink: /themes/:AndroidFirmware/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
